# Generated by Django 2.2.3 on 2019-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_like_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
