# Generated by Django 2.2.3 on 2019-08-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_followers', to='movie_app.User')),
                ('user_followed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_followed', to='movie_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
